name: Password Update Workflow

on:
  workflow_dispatch:
    inputs:
      password_david:
        description: 'David (Enter New password)'
        required: false
      password_warner:
        description: 'Warner (Enter New password)'
        required: false
      environment:
        description: 'Select environment (prod/int)'
        required: true
        default: 'int'
        options:
          - prod
          - int

permissions:
  contents: write

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run password update script
        run: |
          chmod +x password_update.sh
          ./update_passwords.sh "${{ github.event.inputs.environment }}" \
                                "${{ github.event.inputs.password_david }}" \
                                "${{ github.event.inputs.password_warner }}"

      - name: Commit changes to SCM
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated passwords in ${{ github.event.inputs.environment }} environment" || echo "No changes to commit"
          git pull --rebase origin master
          git push origin master
