name: Password update Test Workflow
 
on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 'Enter username'
        required: true
      environment:
        description: 'Select environment (prod/INT)'
        required: true
        default: 'INT'
        type: choice
        options:
          - prod
          - INT

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display Inputs
        run: |
          echo "Username: ${{ github.event.inputs.user_name }}"
          echo "Environment: ${{ github.event.inputs.environment }}"

      - name: Simulate Password Encryption
        id: encrypt_password
        run: |
          echo "Simulating password encryption for ${{ github.event.inputs.user_name }}..."
          # In a real scenario, replace this with actual encryption logic
          encrypted_password=$(echo "password" | openssl enc -aes-256-cbc -a -salt -pass pass:mysecretpass)
          echo "Encrypted password: $encrypted_password"
          echo "::set-output name=encrypted_password::$encrypted_password"
        shell: bash
        
      - name: Simulate Updating Password for Clusters
        run: |
          echo "Updating password for ${{ github.event.inputs.user_name }} in ${{ github.event.inputs.environment }} environment..."
          # Here you would update the clusters (this is just a placeholder)
          echo "Simulated update for all clusters using ${{ github.event.inputs.user_name }}"

      - name: Create or Update XML Files for Clusters
        run: |
          # List of clusters (you can expand this list)
          clusters=("cluster1" "cluster2" "cluster3")
          
          # Create XML files for each cluster
          for cluster in "${clusters[@]}"; do
            xml_file="./${{ github.event.inputs.environment }}/$cluster.xml"
            echo "Creating/Updating $xml_file"
            
            # Create or update the XML file with encrypted password and user info
            cat > $xml_file <<EOL
<cluster>
  <name>$cluster</name>
  <username>${{ github.event.inputs.user_name }}</username>
  <encrypted_password>${{ steps.encrypt_password.outputs.encrypted_password }}</encrypted_password>
</cluster>
EOL
          done

      - name: Commit changes to SCM (Simulation)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git diff --exit-code || (
                git add .
                git commit -m "Update password for ${{ github.event.inputs.user_name }}"
              )
          
              # Only push if there were changes
              if [ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]; then
                git push origin ${{ github.event.inputs.environment }}
              else
                echo "No changes to push."
              fi
