name: Password Update Workflow
on:
  workflow_dispatch:
    inputs:
      user_passwords:
        description: 'Enter passwords for users in JSON format'
        required: true
      environment:
        description: 'Select environment (prod/int)'
        required: true
        default: 'int'
        options:
          - prod
          - int
permissions:
  contents: write

jobs:
  update-password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Parse JSON Input and Run password update script
        run: |
          # Store the JSON input in a variable
          passwords_json='${{ github.event.inputs.user_passwords }}'
          
          # Save the JSON to a file
          echo "$passwords_json" > passwords.json
          
          # Ensure jq is available
          if ! command -v jq &> /dev/null; then
            echo "jq is required but not installed. Exiting."
            exit 1
          fi
          
          # Run the password update script
          chmod +x update_passwords.sh
          ./update_passwords.sh "${{ github.event.inputs.environment }}" passwords.json

      - name: Commit changes to SCM
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated passwords in ${{ github.event.inputs.environment }} environment" || echo "No changes to commit"
          git pull --rebase origin master
          git push origin master
