name: Password Update Workflow
on:
  workflow_dispatch:
    inputs:
      user_passwords:
        description: 'Enter passwords for users in JSON format'
        required: true
      environment:
        description: 'Select environment (prod/int)'
        required: true
        default: 'int'
        options:
          - prod
          - int
permissions:
  contents: write

jobs:
  update-password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Parse and validate JSON Input
        run: |
          # Store the JSON input in a variable
          passwords_json='${{ github.event.inputs.user_passwords }}'
          
          # Validate the JSON input using jq
          echo "$passwords_json" | jq . > passwords.json 2> error.log
          if [ $? -ne 0 ]; then
            echo "Invalid JSON input provided. Error details:"
            cat error.log  # Display the error message from jq
            exit 1
          fi

      - name: Run password update script
        run: |
          # Run the password update script after validation
          chmod +x update_passwords.sh
          ./update_passwords.sh "${{ github.event.inputs.environment }}" passwords.json

      - name: Commit changes to SCM
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated passwords in ${{ github.event.inputs.environment }} environment" || echo "No changes to commit"
          git pull --rebase origin master
          git push origin master
