name: Password Update Workflow

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 'Enter username'
        required: true
      environment:
        description: 'Select environment (prod/INT)'
        required: true
        default: 'int'
        options:
          - prod
          - int

permissions:
  contents: write

jobs:
  update-password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures all history is fetched

      - name: Display Inputs
        run: |
          echo "Username: ${{ github.event.inputs.user_name }}"
          echo "Environment: ${{ github.event.inputs.environment }}"

      - name: Simulate Password Encryption
        id: encrypt_password
        run: |
          echo "Simulating password encryption for ${{ github.event.inputs.user_name }}..."
          encrypted_password=$(echo "password" | openssl enc -aes-256-cbc -a -salt -pass pass:mysecretpass)
          echo "Encrypted password: $encrypted_password"
          echo "encrypted_password=$encrypted_password" >> $GITHUB_OUTPUT
        shell: bash

      - name: Update Password for User in XML Files
        run: |
          username="${{ github.event.inputs.user_name }}"
          env="${{ github.event.inputs.environment }}"
          encrypted_password="${{ steps.encrypt_password.outputs.encrypted_password }}"

          for cluster_dir in apisec invex; do
            xml_file="$cluster_dir/$env.xml"
            if [ -f "$xml_file" ]; then
              echo "Updating $xml_file for user $username"

              # Use sed to replace the password in the matching alias
              sed -i "/<alias name=\"aliasPw${username}\"/s/password=\"[^\"]*\"/password=\"\{RSA:${encrypted_password}\}\"/" "$xml_file"

              echo "Updated password in $xml_file"
            else
              echo "File $xml_file does not exist."
            fi
          done

      - name: Commit changes to SCM
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add .  # Stage all changes
          git commit -m "Updated password for ${{ github.event.inputs.user_name }} in ${{ github.event.inputs.environment }} environment" || echo "No changes to commit"

          git push origin master  # Push to master branch
